name: Run Tests

on:  # Déclencheur : exécute les tests sur chaque push ET pull request
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      # Étape 1 : Clone le dépôt pour accéder au code et aux tests

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.5"  # Même version que dans deploy.yml
      # Étape 2 : Synchronise la version Python avec l'environnement de déploiement

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances principales
        pip install pytest pytest-cov  # Ajoute les outils de test
      # Étape 3 : Installe à la fois les dépendances du projet et des tests

    - name: Run Tests with Coverage
      run: |
        pytest tests/ -v --cov=scripts --cov-report=xml
      # Étape 4 : Exécute :
      # - Tous les tests du dossier tests/
      # - Génère un rapport de couverture (coverage) au format XML
      # --cov=scripts : Mesure la couverture du code dans le dossier scripts/

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Secret à créer dans GitHub
      # Étape 5 : Publie les résultats de couverture sur Codecov
      # (Optionnel : nécessite un compte Codecov gratuit)